// examples/example-react/src/App.tsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import './App.css'
// @ts-ignore
import type { Meta } from '../../example-basic/server'
import { peer } from 'metapoint'

const node = await peer()
const channel = await node.connect<Meta>((window as any)['addr'].reverse())
const plus = await channel("plus")

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
      <div>
        <a href="https://sovlookup.github.io/metapoint" target="_blank">
          <img src="https://sovlookup.github.io/metapoint/logo.svg" className="logo"  alt="Vite logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>MetaPoint + React</h1>
      <p>
       { (window as any).addr.join("\n")}
      </p>
      <div className="card">
        <button onClick={async () => {
            const res = await plus(count)
            return setCount(res[0])
          }}>
          count is {count}
        </button>
      </div>
    </div>
  )
}

export default App

// examples/example-svelte/src/App.svelte
<script lang="ts">
  import svelteLogo from './assets/svelte.svg'
  import Counter from './lib/Counter.svelte'
</script>

<main>
  <div>
    <a
      href="https://sovlookup.github.io/metapoint/"
      target="_blank"
      rel="noreferrer"
    >
      <img
        src="https://sovlookup.github.io/metapoint/logo.svg"
        class="logo"
        alt="MetaPoint Logo"
      />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>MetaPoint + Svelte</h1>

  {window['addr'].join('\n')}
  <div class="card">
    <Counter />
  </div>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #6488ffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
</style>
